[package]
name = "rust_of"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pyo3 = { version = "0.21.2", features = ["extension-module"] }
regex = "1.10.4"
rand = "0.8.5"
gethostname = "0.4.3"
